import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= 'bg-indigo-300'
      >
        <header className="w-full h-[50px] flex items-center px-[25px] justify-between bg-[#7055e9]">
          <h1 className="text-white text-xl font-semibold">DATA FETCH</h1>
          <ul className="flex items-center gap-[25px]">
            <Link href={'./'}><li className="text-white text-md font-bold">Home</li></Link>
            <Link href={'./Clientside'}><li className="text-white text-md font-bold">Client</li></Link>
            <Link href={'./Serverside'}><li className="text-white text-md font-bold">Server</li></Link>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
